### ISSUE TITLE
THIS BROKEN MY PC

### ISSUE THREAD

**Issue by UsboKirishima** [Thebigbot0000/miaofetch#4]
this is a virus absolutely not run this fucking program on your pc.

**Comment by Thebigbot0000** [comment]
Hi @UsboKirishima, I don't think it's a virus, if you install the program as written in the readme simply run a file that creates a file in the path /usr/local/bin named miaofetch with the contents of the file that is in the bin directory. You can check the contents of the file and you can see that it is not a virus. Please remove your "issue". Thank you!
